"""Initial migration.

Revision ID: 941baffe5378
Revises: 
Create Date: 2024-06-28 16:53:03.530281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941baffe5378'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
